source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.1'
gem 'pg'
gem 'authem'
gem 'decent_exposure'

gem 'haml-rails'
gem 'sass-rails', '~> 5.0'
gem 'foundation-rails'
gem 'sprockets'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'active_model_serializers'
gem 'carrierwave'
gem 'fog'
gem 'puma'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'cucumber'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'ffaker'
  gem 'rspec-rails'
  gem 'launchy'
  gem 'selenium-webdriver'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

group :production do
  gem 'aws-sdk', '~> 2'
end
