# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2f7dd406bcbebce738c2abdf86d75c3253343f75adf5b08d79f976d0e0b99b964bff32f4d2aa1546eda5e8f8949b455142c68f3239ccec9d5dabf8097b69055

test:
  secret_key_base: 44db4f15afef66748a3ea369047123e6367c82c71ba6cadd2b0c64d861f950f9fc3f6267af92a29c9327930bd22605908a3ba9f238ca4cbdae72343c40a71fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
